config/routes.rb
Rails.application.routes.draw do
  resources :whales
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
   root 'whales#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/whale.rb
class Whale < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/whales_controller.rb
class WhalesController < ApplicationController
  before_action :set_whale, only: %i[ show edit update destroy ]

  # GET /whales or /whales.json
  def index
    @whales = Whale.all
  end

  # GET /whales/1 or /whales/1.json
  def show
  end

  # GET /whales/new
  def new
    @whale = Whale.new
  end

  # GET /whales/1/edit
  def edit
  end

  # POST /whales or /whales.json
  def create
    @whale = Whale.new(whale_params)

    respond_to do |format|
      if @whale.save
        format.html { redirect_to whale_url(@whale), notice: "Whale was successfully created." }
        format.json { render :show, status: :created, location: @whale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @whale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whales/1 or /whales/1.json
  def update
    respond_to do |format|
      if @whale.update(whale_params)
        format.html { redirect_to whale_url(@whale), notice: "Whale was successfully updated." }
        format.json { render :show, status: :ok, location: @whale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @whale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whales/1 or /whales/1.json
  def destroy
    @whale.destroy

    respond_to do |format|
      format.html { redirect_to whales_url, notice: "Whale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whale
      @whale = Whale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def whale_params
      params.require(:whale).permit(:name, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/whales_helper.rb
module WhalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whaleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/whales/_form.html.erb
<%= form_with(model: whale) do |form| %>
  <% if whale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(whale.errors.count, "error") %> prohibited this whale from being saved:</h2>

      <ul>
        <% whale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/whales/_whale.html.erb
<div id="<%= dom_id whale %>">
  <p>
    <strong>Name:</strong>
    <%= whale.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= whale.facts %>
  </p>

</div>

app/views/whales/edit.html.erb
<h1>Editing whale</h1>

<%= render "form", whale: @whale %>

<br>

<div>
  <%= link_to "Show this whale", @whale %> |
  <%= link_to "Back to whales", whales_path %>
</div>

app/views/whales/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Whales!</h1>

<div id="whales">
  <% @whales.each do |whale| %>
    <%= render whale %>
    <p>
      <%= link_to "Show this whale", whale %>
    </p>
  <% end %>
</div>

<%= link_to "New whale", new_whale_path %>

app/views/whales/new.html.erb
<h1>New whale</h1>

<%= render "form", whale: @whale %>

<br>

<div>
  <%= link_to "Back to whales", whales_path %>
</div>

app/views/whales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @whale %>

<div>
  <%= link_to "Edit this whale", edit_whale_path(@whale) %> |
  <%= link_to "Back to whales", whales_path %>

  <%= button_to "Destroy this whale", @whale, method: :delete %>
</div>